# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install -g npm && npm install -g gulp && pyenv install 3.5-dev && pyenv local 3.5-dev && python -m venv venv # runs during prebuild
#    command: echo 'start script'
