tasks:
  - command: >
      wget https://github.com/CodyHouse/codyhouse-framework/archive/master.zip &&
      unzip master.zip &&
      mv codyhouse-framework-master/** . &&
      rm -R codyhouse-framework-master && 
      rm master.zip &&
      npm install &&
      npm install -g gulp &&
      pyenv install 3.5-dev && pyenv local 3.5-dev &&
      pip install wagtail && wagtail start config .
      