# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install -g npm  # runs during prebuild
  - command: npm install -g gulp
  - command: pyenv install 3.5-dev && pyenv local 3.5-dev && python -m venv venv gp sync-done pipupgrade
  - command: gp sync-await pipupgrade && pip install pip --upgrade