tasks:
  - command: >
      wget https://github.com/CodyHouse/codyhouse-framework/archive/master.zip &&
      unzip master.zip &&
      mv codyhouse-framework-master/** . &&
      rm -R codyhouse-framework-master